Hyderabad Data
pydevsg/Bank-Filter-App pull request #19
Opened 2020-01-10 08:35 UTC by ank1traj

Issue number 7

2020-01-11 07:13 UTC, pydevsg commented
Hi, @ank1traj great work indeed .
Please share a screenshot running it on your local server.
Smae goes for other PRs too.

2020-01-12 17:41 UTC, ank1traj commented
![hyderabad](https://user-images.githubusercontent.com/32160084/72222988-8ae44580-3590-11ea-906a-3e244c4269d6.png)

2020-01-14 05:57 UTC, pydevsg requested changes
@ank1traj please make all the changes as suggested by me.

2020-01-14 05:57 UTC, pydevsg commented on src/Components/Dropdown.js
> +            href = "https://vast-shore-74260.herokuapp.com/banks?city=MUMBAI" >
Please add other cities here, it seems you have written Mumbai thrice which should be written once.

2020-01-14 05:57 UTC, pydevsg commented on src/Components/Dropdown.js
> +              href = "https://vast-shore-74260.herokuapp.com/banks?city=MUMBAI" >
The name of cities should be changed here.

2020-01-14 05:57 UTC, pydevsg commented on src/Components/Dropdown.js
> +                href = "https://vast-shore-74260.herokuapp.com/banks?city=MUMBAI" >
Here too , i.e change the API link as well as city names.

2020-01-14 05:57 UTC, pydevsg commented on src/Components/Dropdown.js
> +                href="https://vast-shore-74260.herokuapp.com/banks?city=MUMBAI"
Same goes for here too.

2020-01-14 05:57 UTC, pydevsg commented on src/Components/Dropdown.js
> +              /a> {
and here

2020-01-14 05:57 UTC, pydevsg commented on src/Components/Table.js
> +      for (let i = 0; i < 5; i++) {
It should be i=0;i<9;

2020-01-14 07:17 UTC, ank1traj commented
Done. Kindly review once again.

2020-04-22 12:58 UTC, closed without merging